INSERT INTO muscle_groups (label, image_url) VALUES
('Abductors', 'https://picsum.photos/200'),
('Abs', 'https://picsum.photos/200'),
('Abductors 2', 'https://picsum.photos/200'),
('Biceps', 'https://picsum.photos/200'),
('Brachialis', 'https://picsum.photos/200'),
('Calves', 'https://picsum.photos/200'),
('Erector Spinae', 'https://picsum.photos/200'),
('Forarms', 'https://picsum.photos/200'),
('Front Shoulders', 'https://picsum.photos/200'),
('Glutes', 'https://picsum.photos/200'),
('Hamstrings', 'https://picsum.photos/200'),
('Hip Flexors', 'https://picsum.photos/200'),
('Infraspinatus', 'https://picsum.photos/200'),
('Lats', 'https://picsum.photos/200'),
('Lower Back', 'https://picsum.photos/200'),
('Lower Chest', 'https://picsum.photos/200'),
('Mid Chest', 'https://picsum.photos/200'),
('Upper Chest', 'https://picsum.photos/200'),
('Mid Shoulders', 'https://picsum.photos/200'),
('Obliques', 'https://picsum.photos/200'),
('Quads', 'https://picsum.photos/200'),
('Rear Shoulders', 'https://picsum.photos/200'),
('Rhomboids', 'https://picsum.photos/200'),
('Subscapularis', 'https://picsum.photos/200'),
('Teres Major', 'https://picsum.photos/200'),
('Transverse Abdominis', 'https://picsum.photos/200'),
('Traps', 'https://picsum.photos/200'),
('Triceps', 'https://picsum.photos/200');


